
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mokleters
 */
public class Frame1 extends javax.swing.JFrame {
 String temp ="";
 Double hl;
    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        knama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ktinggi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kberat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cowok = new javax.swing.JRadioButton();
        cewek = new javax.swing.JRadioButton();
        Hitung = new javax.swing.JButton();
        ulang = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        kideal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        hasil = new javax.swing.JTextField();
        saran = new javax.swing.JTextField();

        jLabel4.setText("jLabel4");

        jRadioButton2.setText("jRadioButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("PERIKSA BERAT BADAN IDEAL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 10, 230, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 60, 40, 20);
        getContentPane().add(knama);
        knama.setBounds(140, 50, 250, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tinggi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 100, 40, 20);
        getContentPane().add(ktinggi);
        ktinggi.setBounds(140, 90, 60, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("cm");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(210, 100, 34, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Berat Badan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 140, 80, 20);
        getContentPane().add(kberat);
        kberat.setBounds(140, 130, 60, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("kg");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(300, 270, 20, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Jenis Kelamin");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 180, 90, 20);

        cowok.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cowok.setText("Laki-laki");
        cowok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cowokActionPerformed(evt);
            }
        });
        getContentPane().add(cowok);
        cowok.setBounds(140, 180, 80, 23);

        cewek.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cewek.setText("Perempuan");
        cewek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cewekActionPerformed(evt);
            }
        });
        getContentPane().add(cewek);
        cewek.setBounds(230, 180, 100, 23);

        Hitung.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        getContentPane().add(Hitung);
        Hitung.setBounds(83, 220, 80, 23);

        ulang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ulang.setText("Coba Lagi");
        ulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulangActionPerformed(evt);
            }
        });
        getContentPane().add(ulang);
        ulang.setBounds(200, 220, 100, 23);

        keluar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(330, 220, 71, 23);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Berat badan ideal Anda adalah");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 270, 210, 20);
        getContentPane().add(kideal);
        kideal.setBounds(250, 260, 40, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("kg");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(210, 140, 20, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 51, 255));
        jLabel11.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(170, 290, 160, 20);

        hasil.setEditable(false);
        getContentPane().add(hasil);
        hasil.setBounds(40, 320, 410, 30);
        getContentPane().add(saran);
        saran.setBounds(40, 360, 410, 30);

        setBounds(0, 0, 502, 452);
    }// </editor-fold>//GEN-END:initComponents

    private void cewekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cewekActionPerformed
        cowok.setSelected(false);
    }//GEN-LAST:event_cewekActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        if(knama.getText().equals("")||ktinggi.getText().equals("")||kberat.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Data harus diisikan semua");
        }
        else if(cowok.isSelected()||jRadioButton2.isSelected())
        {
            try
            {
                Proses();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Inputan ada yang belum diisi");
            }   
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Pilih salah satu jenis kelamin");
        }
    }//GEN-LAST:event_HitungActionPerformed

    private void cowokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cowokActionPerformed
        cewek.setSelected(false);
    }//GEN-LAST:event_cowokActionPerformed

    private void ulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulangActionPerformed
        knama.setText("");
        ktinggi.setText("");
        kberat.setText("");
        cowok.setSelected(false);
        cewek.setSelected(false);
        kideal.setText("");
        hasil.setText("");
        saran.setText("");
    }//GEN-LAST:event_ulangActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hitung;
    private javax.swing.JRadioButton cewek;
    private javax.swing.JRadioButton cowok;
    private javax.swing.JTextField hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField kberat;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField kideal;
    private javax.swing.JTextField knama;
    private javax.swing.JTextField ktinggi;
    private javax.swing.JTextField saran;
    private javax.swing.JButton ulang;
    // End of variables declaration//GEN-END:variables

    private void Proses()
    {
        double ti = Double.parseDouble(ktinggi.getText());
        double bt = Double.parseDouble(kberat.getText());
       
        if(cowok.isSelected())
        {
            hl = (ti - 100) * 1;
        }
        else if(cewek.isSelected())
        {
            hl = (ti - 104) * 1;
        }
        temp = hl+"";
        
        if (hl < bt)
        {
            kideal.setText(temp);
            hasil.setText("Maaf " + knama.getText() + ", sepertinya Anda kelebihan berat badan");
            saran.setText("Banyaklah berolahraga dan hindari makanan berkolesterol");
        }
        else if (hl > bt)
        {
            kideal.setText(temp);
            hasil.setText("Maaf " + knama.getText() + ", sepertinya Anda kekurangan berat badan");
            saran.setText("Banyaklah mengkonsumsi makanan yang berkarbohidrat");
        }
        else
        {
            kideal.setText(temp);
            hasil.setText("Halo " + knama.getText() + ", berat badan Anda sudah cukup");
            saran.setText("Lanjutkan pola makan teratur dan gaya hidup sehat :) ");
        }
    }
}
